### ISSUE TITLE
Add subtask functionality

### ISSUE THREAD

**Issue by samuelmckean** [samuelmckean/todo-list#1]
Add functionality to support having subtasks under each Todo which can be edited, deleted, or completed.

**Comment by samuelmckean** [comment]
- [x] Create Subtask module
- [ ] Provide app functionality to add, remove, edit, and complete subtasks
- [ ]  Ensure subtasks are saved to and loaded from localStorage properly
- [ ] Create ability for user to add, remove, edit, and complete subtasks in the DOM
