### ISSUE TITLE
Add ability to edit Todo

### ISSUE THREAD

**Issue by samuelmckean** [samuelmckean/todo-list#2]
Add the functionality for a user to be able to edit any of the details of a Todo after it has been created.

**Comment by samuelmckean** [comment]
- [x] Create edit button which appears on hovering
- [x] Make clicking the edit button open the editing mode for the todo 
- [x] Remove the delete button onhover
- [x] Make delete button appear in editing mode instead
- [x] Make functionality for delete button to remove the todo

**Comment by samuelmckean** [comment]
Need to deal with case where user tries to add a new todo and edit an existing at the same time
- [x] Change the ids for all the edit todo to be different from a new todo so there is no issue on submit

For now if the user opens both and clicks submit the changes will only be saved for the one that user clicks submit on.

**Comment by samuelmckean** [comment]
- [x] Allow the user to change the fields to blank again during editing
